[workspace]
members = ["beamsrch", "bspa", "sprs"]
resolver = "3"

[workspace.dependencies]
bencher = "0.1.5"
itertools = { version = "0.14.0", default-features = false }
likely_stable = "0.1.3"
log = "0.4.29"
rand = "0.9.2"
rayon = "1.11.0"
rustc-hash = "2.1.1"
